### ISSUE TITLE
Is there a way to test configuration?

### ISSUE THREAD

**Issue by dchersey** [Ardakilic/alerthub#5]
Hello, thank you for putting this together!  I'm running via docker on my dev server and was wondering if there's an easy way to test that it's all working?  I could configure it to monitor one of my own repos and do a release but maybe there's an easier way?

**Comment by dchersey** [comment]
Thanks for the quick response! I'm not using RSS ... basically using SMTP to alert whenever one of my libs is released.  I need to check that it monitors GitHub properly based on my config (just a sanity check, looks pretty straightforward) and that Amazon SES doesn't stop my email due to some missing setting.

**Comment by Ardakilic** [comment]
This application depends on Atom feeds of GitHub actually.

So when you watch something like "Ardakilic/alerthub", I'm actually watching an RSS feed such as

https://github.com/Ardakilic/alerthub/releases.atom

in the application.

Since, In the extras field, you could add any RSS feed, I'd test my configuration (SMTP, Pushbullet settings etc. to make sure I get notified) by providing constantly updating feed to extras field something like I provided.

Apart from that, if you want to check that you want to make sure your configuration (repositories names) is all correct (like, the feeds give me http 200 and they are RSS feeds actually), an extra step could be coded, but there's not a feature like this yet.

But, the aggregator which I use in the application, "rss-feed-emitter", [throws error when URL is invalid or not a feed](https://github.com/filipedeschamps/rss-feed-emitter/blob/master/test/unit/rss-feed-emitter.spec.js#L537-L619), so It shouldn't even boot.

**Comment by dchersey** [comment]
Got it, thanks for the additional info.  Makes sense now.

**Comment by Ardakilic** [comment]
Closing this for the time being. If you have further questions I'll try to help as much as I can.
